### ISSUE TITLE
报一个小bug

### ISSUE THREAD

**Issue by Simon-Wong-hjz** [Philimao/ArkRecordWiki#1]
src/home/LinkBilibili.js中的获取基本信息，请求的地址为http协议，会导致网页无法获取到bilibili的登录信息
```
    <a
          target="_blank"
          rel="noopener noreferrer"
          href="http://api.bilibili.com/x/space/myinfo"
          className="btn btn-outline-secondary"
    >
          获取基本信息
    </a>
```
修改为https即可

**Comment by philimao** [comment]
> src/home/LinkBilibili.js中的获取基本信息，请求的地址为http协议，会导致网页无法获取到bilibili的登录信息
> 
> ```
>     <a
>           target="_blank"
>           rel="noopener noreferrer"
>           href="http://api.bilibili.com/x/space/myinfo"
>           className="btn btn-outline-secondary"
>     >
>           获取基本信息
>     </a>
> ```
> 
> 修改为https即可

感谢！将会尽快更新
