### ISSUE TITLE
域名 arkrec.wiki 的证书配置不正确，返回签发给 *.herokuapp.com 的证书

### ISSUE THREAD

**Issue by GalaxySnail** [Philimao/ArkRecordWiki#2]
如题。访问 `arkrec.wiki` 域名返回的证书不正确，被浏览器警告为不安全，我检查证书后发现证书是签发给 `*.herokuapp.com` 的。应该需要给 `arkrec.wiki` 签发一个正确的证书。

![截图20210607_160736](https://user-images.githubusercontent.com/53637421/120981914-b92c7b80-c7aa-11eb-91bd-7bd4e81beea9.png)

证书公钥指纹：`70ac4c66736ebcaae60e0006adfc661e3c4b1db1`

**Comment by philimao** [comment]
> 如题。访问 `arkrec.wiki` 域名返回的证书不正确，被浏览器警告为不安全，我检查证书后发现证书是签发给 `*.herokuapp.com` 的。应该需要给 `arkrec.wiki` 签发一个正确的证书。
> 
> ![截图20210607_160736](https://user-images.githubusercontent.com/53637421/120981914-b92c7b80-c7aa-11eb-91bd-7bd4e81beea9.png)
> 
> 证书公钥指纹：`70ac4c66736ebcaae60e0006adfc661e3c4b1db1`

感谢提醒，证书之前有尝试过安装，但是不清楚是不是操作不正确，最后因为是免费服务器不能自定义证书作罢。目前主要工作还在完善网站功能，之后会尽快搞定证书的问题。

**Comment by GalaxySnail** [comment]
现在发现域名证书已经正常，所以关闭这个 issue。
